export interface EmojiData {
  emoji: string;
  name: string;
}

export const EMOJIS: EmojiData[] = [
  { emoji: '😀', name: 'grinning face' },
  { emoji: '😃', name: 'smiling face' },
  { emoji: '😄', name: 'beaming face' },
  { emoji: '😁', name: 'grinning with eyes' },
  { emoji: '😆', name: 'squinting laugh' },
  { emoji: '😅', name: 'nervous laugh' },
  { emoji: '🤣', name: 'rolling laugh' },
  { emoji: '😂', name: 'tears of joy' },
  { emoji: '🙂', name: 'slight smile' },
  { emoji: '🙃', name: 'upside down' },
  { emoji: '😉', name: 'winking' },
  { emoji: '😊', name: 'blushing smile' },
  { emoji: '😇', name: 'angel face' },
  { emoji: '😍', name: 'heart eyes' },
  { emoji: '🤩', name: 'star struck' },
  { emoji: '😘', name: 'kissing' },
  { emoji: '😗', name: 'kiss face' },
  { emoji: '😚', name: 'closed eyes kiss' },
  { emoji: '😙', name: 'smiling kiss' },
  { emoji: '😋', name: 'yum face' },
  { emoji: '😛', name: 'tongue out' },
  { emoji: '😜', name: 'winking tongue' },
  { emoji: '🤪', name: 'zany face' },
  { emoji: '😝', name: 'squinting tongue' },
  { emoji: '🤑', name: 'money mouth' },
  { emoji: '🤗', name: 'hugging face' },
  { emoji: '🤭', name: 'hand over mouth' },
  { emoji: '🤫', name: 'shushing face' },
  { emoji: '🤔', name: 'thinking face' },
  { emoji: '🤐', name: 'zipper mouth' },
  { emoji: '🤨', name: 'raised eyebrow' },
  { emoji: '😐', name: 'neutral face' },
  { emoji: '😑', name: 'expressionless' },
  { emoji: '😶', name: 'no mouth' },
  { emoji: '😏', name: 'smirking' },
  { emoji: '😒', name: 'unamused' },
  { emoji: '🙄', name: 'eye roll' },
  { emoji: '😬', name: 'grimacing' },
  { emoji: '🤥', name: 'lying face' },
  { emoji: '😌', name: 'relieved' },
  { emoji: '😔', name: 'pensive' },
  { emoji: '😪', name: 'sleepy' },
  { emoji: '🤤', name: 'drooling' },
  { emoji: '😴', name: 'sleeping' },
  { emoji: '😷', name: 'face mask' },
  { emoji: '🤒', name: 'sick thermometer' },
  { emoji: '🤕', name: 'injured face' },
  { emoji: '🤢', name: 'nauseated' },
  { emoji: '🤮', name: 'vomiting' },
  { emoji: '🤧', name: 'sneezing' },
  { emoji: '😵', name: 'dizzy face' },
  { emoji: '🤯', name: 'exploding head' },
  { emoji: '🤠', name: 'cowboy hat' },
  { emoji: '😎', name: 'cool sunglasses' },
  { emoji: '🤓', name: 'nerd face' },
  { emoji: '🧐', name: 'monocle face' },
  { emoji: '😕', name: 'confused' },
  { emoji: '😟', name: 'worried' },
  { emoji: '🙁', name: 'slight frown' },
  { emoji: '😮', name: 'surprised mouth' },
  { emoji: '😯', name: 'hushed face' },
  { emoji: '😲', name: 'astonished' },
  { emoji: '😳', name: 'flushed face' },
  { emoji: '😦', name: 'frowning mouth' },
  { emoji: '😧', name: 'anguished' },
  { emoji: '😨', name: 'fearful' },
  { emoji: '😰', name: 'anxious sweat' },
  { emoji: '😥', name: 'sad sweat' },
  { emoji: '😢', name: 'crying face' },
  { emoji: '😭', name: 'loudly crying' },
  { emoji: '😱', name: 'screaming fear' },
  { emoji: '😖', name: 'confounded' },
  { emoji: '😣', name: 'persevering' },
  { emoji: '😞', name: 'disappointed' },
  { emoji: '😓', name: 'downcast sweat' },
  { emoji: '😩', name: 'weary' },
  { emoji: '😫', name: 'tired face' },
  { emoji: '😤', name: 'triumph steam' },
  { emoji: '😡', name: 'pouting angry' },
  { emoji: '😠', name: 'angry face' },
  { emoji: '🤬', name: 'cursing symbols' },
  { emoji: '😈', name: 'smiling devil' },
  { emoji: '👿', name: 'angry devil' },
];

export function getRandomEmoji(): EmojiData {
  const randomIndex = Math.floor(Math.random() * EMOJIS.length);
  return EMOJIS[randomIndex];
}

